### PR TITLE
[Feature #158423067] Add view rides page

### PR DESCRIPTION
**Pull request by Xerrex**
#### This pull request:
* Adds a  page to view all the available rides.
view all rides

### CODE REVIEW

**Comment by artorious** [comment]
Looks good bruv. 
Consider using the recommended [Pull request format](https://quickleft.com/blog/pull-request-templates-make-code-review-easier/) . Enables the reviewer to better understand what your changes  are about.

**Comment by evamaina** [comment]
looks nice

**Comment by meshack-mbuvi** [comment]
The ui looks cool. Observe what @artorious has mentioned.

**Comment by Xerrex** [comment]
I am checking out the PR format right away.

**Comment by Xerrex** [comment]
The PR format will be implemented in my next PR

**Pull request merged**
