### PR TITLE
Ft sign up 158422156

### PR DESCRIPTION
**Pull request by Xerrex**
## This pull request contains:
* Adding a landing page
* Sign up form 
landing page

### CODE REVIEW

**Comment by Quantum-35** [comment]
Look good to me

**Comment by benlegendj** [comment]
Its a good one

**Comment by evamaina** [comment]
looking nice. Maybe it would look much better if the signup form and the image are aligned at the same level.My opinion

**Comment by TheSteelGuy** [comment]
attractive UI

**Pull request merged**
